AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'

Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Max: 150
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Layout/LineLength:
  Max: 150
